Symbol Table: *****************
        name  line        type   attribute
        sort    15   procedure
           j    12    sys_type     integer
        ZERO     3       const     integer           0
           i    12    sys_type     integer
        temp    13    sys_type     integer
     MAX_LEN     4       const     integer         100
----------------------------------------
procedure: "sort"
        name  line        type   attribute
        size    17    sys_type     integer
        name  line        type   attribute
         arr    16       array       range    0 .. 100
                                  sys_type     integer
Type of AST Node: *****************
type of id: 46
    sys_type     integer
type of id: 47
    sys_type     integer
type of id: 48
    sys_type     integer
type of id: 49
    sys_type     integer
type of id: 50
    sys_type     integer
type of id: 52
    sys_type     integer
type of id: 53
    sys_type     integer
type of id: 54
    sys_type     integer
type of id: 56
    sys_type     boolean
type of id: 57
    sys_type     integer
type of id: 58
       array       range    0 .. 100
                sys_type     integer
type of id: 59
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 61
       array       range    0 .. 100
                sys_type     integer
type of id: 62
    sys_type     integer
type of id: 63
    sys_type     integer
type of id: 64
    sys_type     integer
type of id: 67
    sys_type     integer
type of id: 68
    sys_type     integer
type of id: 69
    sys_type     integer
type of id: 70
       array       range    0 .. 100
                sys_type     integer
type of id: 71
    sys_type     integer
type of id: 72
    sys_type     integer
type of id: 73
    sys_type     integer
type of id: 74
       array       range    0 .. 100
                sys_type     integer
type of id: 75
    sys_type     integer
type of id: 76
    sys_type     integer
type of id: 77
       array       range    0 .. 100
                sys_type     integer
type of id: 78
    sys_type     integer
type of id: 79
    sys_type     integer
type of id: 80
    sys_type     integer
type of id: 81
    sys_type     integer
type of id: 82
    sys_type     integer
type of id: 83
       array       range    0 .. 100
                sys_type     integer
type of id: 84
    sys_type     integer
type of id: 85
    sys_type     integer
type of id: 86
    sys_type     integer
type of id: 87
    sys_type     integer
