Symbol Table: *****************
        name  line        type   attribute
        sort    16   procedure
     integer     0    sys_type     integer
        real     0    sys_type        real
      Vector     8      record         arr:        array       range    0 .. 100
                                                            sys_type     integer
                                      size:     sys_type     integer
           j    13    sys_type     integer
        ZERO     4       const     integer           0
           i    13    sys_type     integer
       Array     7       array       range    0 .. 100
                                  sys_type     integer
        temp    14    sys_type     integer
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
     MAX_LEN     5       const     integer         100
----------------------------------------
procedure: "sort"
        name  line        type   attribute
         arr    17       array       range    0 .. 100
                                  sys_type     integer
        name  line        type   attribute
        size    18    sys_type     integer
Type of AST Node: *****************
type of id: 46
    sys_type     integer
type of id: 47
    sys_type     integer
type of id: 48
    sys_type     integer
type of id: 49
    sys_type     integer
type of id: 50
    sys_type     integer
type of id: 52
    sys_type     integer
type of id: 53
    sys_type     integer
type of id: 54
    sys_type     integer
type of id: 56
    sys_type     boolean
type of id: 57
    sys_type     integer
type of id: 58
       array       range    0 .. 100
                sys_type     integer
type of id: 59
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 61
       array       range    0 .. 100
                sys_type     integer
type of id: 62
    sys_type     integer
type of id: 63
    sys_type     integer
type of id: 64
    sys_type     integer
type of id: 67
    sys_type     integer
type of id: 68
    sys_type     integer
type of id: 69
    sys_type     integer
type of id: 70
       array       range    0 .. 100
                sys_type     integer
type of id: 71
    sys_type     integer
type of id: 72
    sys_type     integer
type of id: 73
    sys_type     integer
type of id: 74
       array       range    0 .. 100
                sys_type     integer
type of id: 75
    sys_type     integer
type of id: 76
    sys_type     integer
type of id: 77
       array       range    0 .. 100
                sys_type     integer
type of id: 78
    sys_type     integer
type of id: 79
    sys_type     integer
type of id: 80
    sys_type     integer
type of id: 81
    sys_type     integer
type of id: 82
    sys_type     integer
type of id: 83
       array       range    0 .. 100
                sys_type     integer
type of id: 84
    sys_type     integer
type of id: 85
    sys_type     integer
type of id: 86
    sys_type     integer
type of id: 87
    sys_type     integer
