Symbol Table: *****************
        name  line        type   attribute
        Math     6        enum        Math, Math, English, 
       Grade     6       array        enum        Math, Math, English, 
                                  sys_type        real
          PI     4       const        real     3.14159
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
     Student     7      record         age:     sys_type     integer
                                   m_Grade:        array        enum        Math, Math, English, 
                                                            sys_type        real
        real     0    sys_type        real
     English     6        enum        Math, Math, English, 
        ZERO     3       const     integer           0
     integer     0    sys_type     integer
Type of AST Node: *****************
