Symbol Table: *****************
        name  line        type   attribute
         avg     0    sys_type        real
        temp     0    sys_type     integer
       count     0    sys_type     integer
       total     0    sys_type     integer
Type of AST Node: *****************
type of id: 20
    sys_type     boolean
type of id: 21
    sys_type     integer
type of id: 22
    sys_type     integer
type of id: 27
    sys_type      string
type of id: 28
    sys_type     integer
type of id: 29
    sys_type     integer
type of id: 30
    sys_type     integer
type of id: 31
    sys_type     integer
type of id: 32
    sys_type     integer
type of id: 33
    sys_type     integer
type of id: 34
    sys_type     integer
type of id: 35
    sys_type     integer
type of id: 36
    sys_type     integer
type of id: 37
    sys_type     integer
type of id: 38
    sys_type     integer
type of id: 39
    sys_type     integer
type of id: 40
    sys_type     integer
type of id: 41
    sys_type     integer
type of id: 42
    sys_type     integer
type of id: 43
    sys_type     integer
type of id: 44
    sys_type        real
type of id: 45
    sys_type        real
type of id: 46
    sys_type        real
type of id: 47
    sys_type        real
type of id: 48
    sys_type        real
type of id: 49
    sys_type     integer
type of id: 50
    sys_type     integer
type of id: 53
    sys_type        real
