Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
       value     2    sys_type     integer
Type of AST Node: *****************
type of id: 20
    sys_type      string
type of id: 23
    sys_type      string
type of id: 24
    sys_type     integer
type of id: 26
    sys_type     boolean
type of id: 27
    sys_type     integer
type of id: 28
    sys_type     integer
type of id: 30
    sys_type     integer
type of id: 32
    sys_type     boolean
type of id: 33
    sys_type     integer
type of id: 34
    sys_type     integer
type of id: 36
    sys_type     integer
type of id: 38
    sys_type     boolean
type of id: 39
    sys_type     integer
type of id: 40
    sys_type     integer
type of id: 42
    sys_type     integer
type of id: 44
    sys_type     integer
type of id: 47
    sys_type      string
type of id: 48
    sys_type     integer
type of id: 50
    sys_type     integer
type of id: 52
    sys_type     integer
type of id: 55
    sys_type      string
type of id: 56
    sys_type     integer
type of id: 58
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 63
    sys_type      string
type of id: 64
    sys_type     integer
type of id: 66
    sys_type     integer
type of id: 68
    sys_type     integer
type of id: 71
    sys_type      string
