Symbol Table: *****************
        name  line        type   attribute
        fibo     9    function      record      fibo_n:     sys_type     integer
                                               n_steps:     sys_type     integer
        temp     8      record      fibo_n:     sys_type     integer
                                   n_steps:     sys_type     integer
         ans     5      record      fibo_n:     sys_type     integer
                                   n_steps:     sys_type     integer
      string     0    sys_type      string
        char     0    sys_type        char
         int     4    sys_type     integer
     boolean     0    sys_type     boolean
        real     0    sys_type        real
     integer     0    sys_type     integer
----------------------------------------
function: "fibo"
        name  line        type   attribute
           n    10    sys_type     integer
Type of AST Node: *****************
type of id: 29
    sys_type     boolean
type of id: 30
    sys_type     integer
type of id: 31
    sys_type     integer
type of id: 33
    sys_type     integer
type of id: 34
    sys_type     integer
type of id: 37
    sys_type     integer
type of id: 38
    sys_type     integer
type of id: 39
    sys_type     integer
type of id: 42
    sys_type     integer
type of id: 49
    sys_type     integer
type of id: 50
    sys_type     integer
type of id: 53
    sys_type     integer
type of id: 54
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 55
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 56
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 58
    sys_type     integer
type of id: 59
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 61
    sys_type     integer
type of id: 62
    sys_type     integer
type of id: 65
    sys_type     integer
type of id: 66
    sys_type     integer
type of id: 69
    sys_type     integer
type of id: 70
    sys_type     integer
type of id: 71
    sys_type     integer
type of id: 74
    sys_type     integer
type of id: 77
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 78
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 79
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 81
    sys_type     integer
type of id: 82
    sys_type     integer
type of id: 83
    sys_type     integer
type of id: 84
    sys_type     integer
type of id: 85
    sys_type     integer
type of id: 88
    sys_type     integer
type of id: 89
    sys_type     integer
type of id: 92
    sys_type     integer
type of id: 95
    sys_type     integer
type of id: 96
    sys_type     integer
type of id: 99
    sys_type     integer
type of id: 100
    sys_type     integer
type of id: 103
    sys_type     integer
