Symbol Table: *****************
        name  line        type   attribute
        fibo     0    function    sys_type     integer
        info     0      record      fibo_n:     sys_type     integer
                                   n_steps:     sys_type     integer
           n     0    sys_type     integer
----------------------------------------
function: "fibo"
        name  line        type   attribute
           n     0    sys_type     integer
        name  line        type   attribute
        info     0      record      fibo_n:     sys_type     integer
                                   n_steps:     sys_type     integer
Type of AST Node: *****************
type of id: 32
    sys_type     integer
type of id: 33
    sys_type     integer
type of id: 36
    sys_type     integer
type of id: 37
    sys_type     integer
type of id: 40
    sys_type     integer
type of id: 42
    sys_type     boolean
type of id: 43
    sys_type     integer
type of id: 44
    sys_type     integer
type of id: 46
    sys_type     integer
type of id: 47
    sys_type     integer
type of id: 48
    sys_type     integer
type of id: 49
    sys_type     integer
type of id: 50
    sys_type     integer
type of id: 53
    sys_type     integer
type of id: 55
    sys_type     integer
type of id: 56
    sys_type     integer
type of id: 57
    sys_type     integer
type of id: 58
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 61
    sys_type     integer
type of id: 62
    sys_type     integer
type of id: 63
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 64
    sys_type     integer
type of id: 66
    sys_type     integer
type of id: 67
    sys_type     integer
type of id: 68
    sys_type     integer
type of id: 69
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 70
    sys_type     integer
type of id: 71
    sys_type     integer
type of id: 74
    sys_type     integer
type of id: 79
    sys_type     integer
type of id: 80
    sys_type     integer
type of id: 83
    sys_type     integer
type of id: 86
    sys_type      string
type of id: 87
    sys_type     integer
type of id: 90
    sys_type      string
type of id: 91
    sys_type     integer
type of id: 92
    sys_type      string
type of id: 93
    sys_type     integer
type of id: 95
    sys_type     integer
type of id: 96
      record      fibo_n:     sys_type     integer
                 n_steps:     sys_type     integer
type of id: 99
    sys_type      string
type of id: 100
    sys_type     integer
type of id: 103
    sys_type      string
