Symbol Table: *****************
        name  line        type   attribute
        date     0      record         Day:     sys_type     integer
                                     Month:     sys_type     integer
                                      Year:     sys_type     integer
    get_date     0    function    sys_type      string
----------------------------------------
function: "get_date"
        name  line        type   attribute
        date     0      record         Day:     sys_type     integer
                                     Month:     sys_type     integer
                                      Year:     sys_type     integer
Type of AST Node: *****************
type of id: 25
    sys_type     integer
type of id: 30
    sys_type     integer
type of id: 31
    sys_type      string
type of id: 32
    sys_type      string
type of id: 33
    sys_type      string
type of id: 35
    sys_type     integer
type of id: 36
    sys_type      string
type of id: 37
    sys_type      string
type of id: 38
    sys_type      string
type of id: 40
    sys_type     integer
type of id: 41
    sys_type      string
type of id: 42
    sys_type      string
type of id: 43
    sys_type      string
type of id: 45
    sys_type     integer
type of id: 46
    sys_type      string
type of id: 47
    sys_type      string
type of id: 48
    sys_type      string
type of id: 50
    sys_type     integer
type of id: 51
    sys_type      string
type of id: 52
    sys_type      string
type of id: 53
    sys_type      string
type of id: 55
    sys_type     integer
type of id: 56
    sys_type      string
type of id: 57
    sys_type      string
type of id: 58
    sys_type      string
type of id: 60
    sys_type     integer
type of id: 61
    sys_type      string
type of id: 62
    sys_type      string
type of id: 63
    sys_type      string
type of id: 70
    sys_type      string
type of id: 71
    sys_type     integer
type of id: 76
    sys_type      string
type of id: 77
    sys_type     integer
type of id: 82
    sys_type      string
type of id: 83
    sys_type     integer
type of id: 88
    sys_type      string
type of id: 90
      record         Day:     sys_type     integer
                   Month:     sys_type     integer
                    Year:     sys_type     integer
