Symbol Table: *****************
        name  line        type   attribute
        Date     3      record         Day:     sys_type     integer
                                     Month:     sys_type     integer
                                      Year:     sys_type     integer
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
        real     0    sys_type        real
    get_date     7    function    sys_type      string
     integer     0    sys_type     integer
----------------------------------------
function: "get_date"
        name  line        type   attribute
        date     8      record         Day:     sys_type     integer
                                     Month:     sys_type     integer
                                      Year:     sys_type     integer
Type of AST Node: *****************
type of id: 21
    sys_type     integer
type of id: 26
    sys_type     integer
type of id: 27
    sys_type      string
type of id: 28
    sys_type      string
type of id: 29
    sys_type      string
type of id: 31
    sys_type     integer
type of id: 32
    sys_type      string
type of id: 33
    sys_type      string
type of id: 34
    sys_type      string
type of id: 36
    sys_type     integer
type of id: 37
    sys_type      string
type of id: 38
    sys_type      string
type of id: 39
    sys_type      string
type of id: 41
    sys_type     integer
type of id: 42
    sys_type      string
type of id: 43
    sys_type      string
type of id: 44
    sys_type      string
type of id: 46
    sys_type     integer
type of id: 47
    sys_type      string
type of id: 48
    sys_type      string
type of id: 49
    sys_type      string
type of id: 51
    sys_type     integer
type of id: 52
    sys_type      string
type of id: 53
    sys_type      string
type of id: 54
    sys_type      string
type of id: 56
    sys_type     integer
type of id: 57
    sys_type      string
type of id: 58
    sys_type      string
type of id: 59
    sys_type      string
