Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
       input     6    sys_type     integer
      number     4    sys_type     integer
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
        real     0    sys_type        real
       times     5    sys_type     integer
     integer     0    sys_type     integer
Type of AST Node: *****************
type of id: 16
    sys_type     integer
type of id: 17
    sys_type     integer
type of id: 18
    sys_type     integer
type of id: 19
    sys_type     integer
type of id: 20
    sys_type     integer
type of id: 21
    sys_type     integer
type of id: 23
    sys_type     boolean
type of id: 24
    sys_type     integer
type of id: 29
    sys_type     integer
type of id: 30
    sys_type     integer
type of id: 31
    sys_type     integer
type of id: 32
    sys_type     integer
type of id: 33
    sys_type     integer
type of id: 36
    sys_type      string
type of id: 39
    sys_type      string
type of id: 40
    sys_type     integer
type of id: 41
    sys_type      string
