Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
      string     0    sys_type      string
        char     0    sys_type        char
         str     3       const      string   "Hello World!"
     boolean     0    sys_type     boolean
        real     0    sys_type        real
     integer     0    sys_type     integer
Type of AST Node: *****************
type of id: 9
    sys_type      string
