Symbol Table: *****************
        name  line        type   attribute
     is_even     0    function    sys_type     boolean
       input     0    sys_type     integer
        zero     0       const     integer           0
----------------------------------------
function: "is_even"
        name  line        type   attribute
         num     0    sys_type     integer
Type of AST Node: *****************
type of id: 23
    sys_type      string
type of id: 24
    sys_type     integer
type of id: 25
    sys_type      string
type of id: 26
    sys_type     integer
type of id: 28
    sys_type     integer
type of id: 29
    sys_type     integer
type of id: 30
    sys_type     integer
type of id: 31
    sys_type     integer
type of id: 33
    sys_type     integer
type of id: 35
    sys_type     integer
type of id: 36
    sys_type     integer
type of id: 37
    sys_type     integer
type of id: 40
    sys_type     integer
type of id: 41
    sys_type     boolean
type of id: 42
    sys_type     boolean
type of id: 43
    sys_type     boolean
type of id: 45
    sys_type     integer
type of id: 46
    sys_type     boolean
type of id: 47
    sys_type     boolean
type of id: 48
    sys_type     boolean
type of id: 53
    sys_type      string
type of id: 54
    sys_type     integer
type of id: 56
    sys_type     boolean
type of id: 58
    sys_type     integer
type of id: 61
    sys_type      string
type of id: 62
    sys_type     integer
type of id: 63
    sys_type      string
type of id: 66
    sys_type      string
type of id: 67
    sys_type     integer
type of id: 68
    sys_type      string
