Symbol Table: *****************
        name  line        type   attribute
       value     0    sys_type        real
          pi     0       const        real     3.14159
Type of AST Node: *****************
type of id: 15
    sys_type      string
type of id: 16
    sys_type        real
type of id: 18
    sys_type     boolean
type of id: 19
    sys_type        real
type of id: 20
    sys_type        real
type of id: 23
    sys_type        real
type of id: 24
    sys_type      string
type of id: 25
    sys_type        real
type of id: 28
    sys_type        real
type of id: 29
    sys_type      string
type of id: 30
    sys_type        real
type of id: 33
    sys_type      string
