Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
       index     6    sys_type     integer
      factor     5    sys_type        real
       steps     7    sys_type     integer
        temp     4    sys_type        real
          pi     3    sys_type        real
Type of AST Node: *****************
type of id: 26
    sys_type      string
type of id: 29
    sys_type      string
type of id: 30
    sys_type     integer
type of id: 31
    sys_type     integer
type of id: 32
    sys_type     integer
type of id: 33
    sys_type     integer
type of id: 34
    sys_type        real
type of id: 35
    sys_type        real
type of id: 36
    sys_type     integer
type of id: 37
    sys_type        real
type of id: 38
    sys_type        real
type of id: 39
    sys_type     integer
type of id: 41
    sys_type     boolean
type of id: 42
    sys_type     integer
type of id: 43
    sys_type     integer
type of id: 48
    sys_type        real
type of id: 49
    sys_type        real
type of id: 50
    sys_type     integer
type of id: 51
    sys_type     integer
type of id: 52
    sys_type     integer
type of id: 53
    sys_type        real
type of id: 54
    sys_type        real
type of id: 55
    sys_type        real
type of id: 56
    sys_type        real
type of id: 57
    sys_type        real
type of id: 58
    sys_type        real
type of id: 59
    sys_type        real
type of id: 60
    sys_type        real
type of id: 61
    sys_type        real
type of id: 62
    sys_type        real
type of id: 63
    sys_type        real
type of id: 64
    sys_type        real
type of id: 65
    sys_type        real
type of id: 66
    sys_type     integer
type of id: 67
    sys_type        real
type of id: 68
    sys_type        real
type of id: 69
    sys_type        real
type of id: 70
    sys_type        real
type of id: 71
    sys_type     integer
type of id: 72
    sys_type        real
type of id: 73
    sys_type        real
type of id: 74
    sys_type        real
type of id: 75
    sys_type        real
type of id: 76
    sys_type     integer
type of id: 77
    sys_type        real
type of id: 78
    sys_type        real
type of id: 79
    sys_type        real
type of id: 80
    sys_type        real
type of id: 81
    sys_type     integer
type of id: 82
    sys_type     integer
type of id: 83
    sys_type     integer
type of id: 84
    sys_type     integer
type of id: 85
    sys_type     integer
type of id: 86
    sys_type     integer
type of id: 87
    sys_type        real
type of id: 88
    sys_type        real
type of id: 89
    sys_type        real
type of id: 90
    sys_type        real
type of id: 91
    sys_type     integer
type of id: 94
    sys_type      string
type of id: 95
    sys_type        real
type of id: 96
    sys_type     integer
type of id: 97
    sys_type     integer
