Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
       value     5    sys_type        real
          pi     3       const        real     3.14159
Type of AST Node: *****************
type of id: 16
    sys_type      string
type of id: 19
    sys_type      string
type of id: 20
    sys_type        real
type of id: 22
    sys_type     boolean
type of id: 23
    sys_type        real
type of id: 24
    sys_type        real
type of id: 27
    sys_type      string
type of id: 28
    sys_type        real
type of id: 29
    sys_type        real
type of id: 32
    sys_type      string
type of id: 33
    sys_type        real
type of id: 34
    sys_type        real
type of id: 37
    sys_type      string
