Symbol Table: *****************
        name  line        type   attribute
    greeting     0   procedure
        name     0    sys_type      string
----------------------------------------
procedure: "greeting"
        name  line        type   attribute
          id     0    sys_type     integer
        name  line        type   attribute
        name     0    sys_type      string
Type of AST Node: *****************
type of id: 20
    sys_type      string
type of id: 21
    sys_type      string
type of id: 24
    sys_type      string
type of id: 25
    sys_type     integer
type of id: 28
    sys_type      string
type of id: 29
    sys_type      string
type of id: 30
    sys_type      string
type of id: 33
    sys_type      string
type of id: 34
    sys_type     integer
