Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
    greeting     5   procedure
        name     3    sys_type      string
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
        real     0    sys_type        real
     integer     0    sys_type     integer
----------------------------------------
procedure: "greeting"
        name  line        type   attribute
        name     6    sys_type      string
        name  line        type   attribute
          id     7    sys_type     integer
Type of AST Node: *****************
type of id: 19
    sys_type      string
type of id: 20
    sys_type      string
type of id: 21
    sys_type      string
type of id: 22
    sys_type     integer
type of id: 25
    sys_type      string
type of id: 26
    sys_type      string
type of id: 27
    sys_type      string
type of id: 30
    sys_type      string
type of id: 31
    sys_type     integer
