Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
           x     3    sys_type     integer
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
        real     0    sys_type        real
     integer     0    sys_type     integer
Type of AST Node: *****************
type of id: 10
    sys_type     integer
type of id: 13
    sys_type        real
type of id: 15
    sys_type     integer
