Symbol Table: *****************
        name  line        type   attribute
mySquareRoot     0    function    sys_type        real
         eps     0    sys_type        real
           x     0    sys_type        real
         EPS     0    sys_type        real
----------------------------------------
function: "mySquareRoot"
        name  line        type   attribute
         EPS     0    sys_type        real
           x     0    sys_type        real
        name  line        type   attribute
         eps     0    sys_type        real
Type of AST Node: *****************
type of id: 28
    sys_type        real
type of id: 29
    sys_type        real
type of id: 30
    sys_type        real
type of id: 32
    sys_type     boolean
type of id: 33
    sys_type        real
type of id: 34
    sys_type        real
type of id: 36
    sys_type        real
type of id: 37
    sys_type        real
type of id: 38
    sys_type        real
type of id: 39
    sys_type        real
type of id: 40
    sys_type        real
type of id: 41
    sys_type        real
type of id: 42
    sys_type        real
type of id: 43
    sys_type        real
type of id: 44
    sys_type     integer
type of id: 45
    sys_type        real
type of id: 46
    sys_type        real
type of id: 47
    sys_type        real
type of id: 48
    sys_type        real
type of id: 50
    sys_type        real
type of id: 51
    sys_type        real
type of id: 59
    sys_type      string
type of id: 60
    sys_type        real
type of id: 63
    sys_type      string
type of id: 64
    sys_type        real
type of id: 67
    sys_type      string
type of id: 68
    sys_type        real
type of id: 69
    sys_type      string
type of id: 70
    sys_type        real
type of id: 72
    sys_type        real
type of id: 73
    sys_type        real
type of id: 74
    sys_type        real
type of id: 77
    sys_type      string
type of id: 78
    sys_type        real
type of id: 81
    sys_type      string
type of id: 82
    sys_type        real
type of id: 83
    sys_type      string
type of id: 84
    sys_type        real
type of id: 86
    sys_type        real
