Symbol Table: *****************
        name  line        type   attribute
        swap     0   procedure
        temp     0    sys_type        real
           x     0    sys_type        real
           y     0    sys_type        real
----------------------------------------
procedure: "swap"
        name  line        type   attribute
        temp     0    sys_type        real
        name  line        type   attribute
           y     0    sys_type        real
           x     0    sys_type        real
Type of AST Node: *****************
type of id: 26
    sys_type        real
type of id: 27
    sys_type        real
type of id: 28
    sys_type        real
type of id: 29
    sys_type        real
type of id: 30
    sys_type        real
type of id: 31
    sys_type        real
type of id: 32
    sys_type        real
type of id: 33
    sys_type        real
type of id: 34
    sys_type        real
type of id: 42
    sys_type      string
type of id: 43
    sys_type        real
type of id: 46
    sys_type      string
type of id: 47
    sys_type        real
type of id: 50
    sys_type        real
type of id: 51
    sys_type        real
type of id: 52
    sys_type        real
type of id: 55
    sys_type      string
type of id: 58
    sys_type      string
type of id: 59
    sys_type        real
type of id: 60
    sys_type      string
type of id: 61
    sys_type        real
