Symbol Table: *****************
        name  line        type   attribute
        swap     8    function    sys_type     integer
      string     0    sys_type      string
        temp     6    sys_type        real
       Color     3       array        enum         red, green, blue, 
                                  sys_type        real
  temp_color     7       array        enum         red, green, blue, 
                                  sys_type        real
        blue     3        enum         red, green, blue, 
         red     3        enum         red, green, blue, 
  Color_list     4       array       range    1 .. 100
                                     array        enum         red, green, blue, 
                                              sys_type        real
        char     0    sys_type        char
     integer     0    sys_type     integer
        real     0    sys_type        real
       green     3        enum         red, green, blue, 
     boolean     0    sys_type     boolean
----------------------------------------
function: "swap"
        name  line        type   attribute
      color2    10       array        enum         red, green, blue, 
                                  sys_type        real
      color1    10       array        enum         red, green, blue, 
                                  sys_type        real
        name  line        type   attribute
       list2    11       array       range    1 .. 100
                                     array        enum         red, green, blue, 
                                              sys_type        real
       list1    11       array       range    1 .. 100
                                     array        enum         red, green, blue, 
                                              sys_type        real
Type of AST Node: *****************
type of id: 45
    sys_type        real
type of id: 46
    sys_type        real
type of id: 47
    sys_type        real
type of id: 48
       array        enum         red, green, blue, 
                sys_type        real
type of id: 49
        enum         red, green, blue, 
type of id: 50
    sys_type        real
type of id: 51
    sys_type        real
type of id: 52
       array        enum         red, green, blue, 
                sys_type        real
type of id: 53
        enum         red, green, blue, 
type of id: 54
    sys_type        real
type of id: 55
       array        enum         red, green, blue, 
                sys_type        real
type of id: 56
        enum         red, green, blue, 
type of id: 57
    sys_type        real
type of id: 58
    sys_type        real
type of id: 59
       array        enum         red, green, blue, 
                sys_type        real
type of id: 60
        enum         red, green, blue, 
type of id: 61
    sys_type        real
type of id: 62
       array        enum         red, green, blue, 
                sys_type        real
type of id: 63
       array        enum         red, green, blue, 
                sys_type        real
type of id: 64
       array        enum         red, green, blue, 
                sys_type        real
type of id: 65
       array       range    1 .. 100
                   array        enum         red, green, blue, 
                            sys_type        real
type of id: 66
    sys_type     integer
type of id: 67
       array        enum         red, green, blue, 
                sys_type        real
type of id: 68
       array        enum         red, green, blue, 
                sys_type        real
type of id: 69
       array       range    1 .. 100
                   array        enum         red, green, blue, 
                            sys_type        real
type of id: 70
    sys_type     integer
type of id: 71
       array        enum         red, green, blue, 
                sys_type        real
type of id: 72
       array       range    1 .. 100
                   array        enum         red, green, blue, 
                            sys_type        real
type of id: 73
    sys_type     integer
type of id: 74
       array        enum         red, green, blue, 
                sys_type        real
type of id: 75
       array        enum         red, green, blue, 
                sys_type        real
type of id: 76
       array       range    1 .. 100
                   array        enum         red, green, blue, 
                            sys_type        real
type of id: 77
    sys_type     integer
type of id: 78
       array        enum         red, green, blue, 
                sys_type        real
type of id: 79
    sys_type     integer
type of id: 80
    sys_type     integer
type of id: 81
    sys_type     integer
