Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
       value    10    sys_type        real
       index     9    sys_type     integer
        bool     7    sys_type     boolean
           T     5       const     boolean           1
          pi     3       const        real     3.14159
    testBool    11    sys_type     boolean
           t     4       const     integer           3
Type of AST Node: *****************
type of id: 34
    sys_type      string
type of id: 37
    sys_type      string
type of id: 38
    sys_type     integer
type of id: 39
    sys_type     integer
type of id: 40
    sys_type     integer
type of id: 41
    sys_type     integer
type of id: 42
    sys_type     integer
type of id: 43
    sys_type     integer
type of id: 44
    sys_type        real
type of id: 45
    sys_type        real
type of id: 46
    sys_type        real
type of id: 47
    sys_type        real
type of id: 48
    sys_type        real
type of id: 49
    sys_type        real
type of id: 50
    sys_type        real
type of id: 51
    sys_type     integer
type of id: 52
    sys_type        real
type of id: 53
    sys_type     integer
type of id: 54
    sys_type        real
type of id: 55
    sys_type     boolean
type of id: 56
    sys_type     boolean
type of id: 57
    sys_type     boolean
type of id: 58
    sys_type     boolean
type of id: 59
    sys_type     boolean
type of id: 60
    sys_type     boolean
type of id: 61
    sys_type     boolean
type of id: 62
    sys_type     boolean
type of id: 65
    sys_type      string
type of id: 66
    sys_type     integer
type of id: 67
    sys_type        real
type of id: 68
    sys_type     boolean
