Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
        wrap    15    function    sys_type     integer
        temp    13    sys_type     integer
        info    12      record         Age:     sys_type     integer
                                       GPA:     sys_type        real
                                      Name:     sys_type      string
----------------------------------------
function: "wrap"
        name  line        type   attribute
         GPA    18    sys_type        real
        Name    17    sys_type      string
         Age    16    sys_type     integer
Type of AST Node: *****************
type of id: 42
    sys_type     integer
type of id: 43
    sys_type     integer
type of id: 46
    sys_type     integer
type of id: 47
    sys_type      string
type of id: 48
    sys_type      string
type of id: 51
    sys_type      string
type of id: 52
    sys_type        real
type of id: 53
    sys_type        real
type of id: 56
    sys_type        real
type of id: 59
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 61
    sys_type     integer
type of id: 63
    sys_type     integer
type of id: 64
    sys_type      string
type of id: 65
    sys_type        real
type of id: 68
    sys_type      string
type of id: 69
    sys_type      string
type of id: 72
    sys_type      string
type of id: 73
    sys_type     integer
type of id: 76
    sys_type      string
type of id: 77
    sys_type        real
