Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
         tmp     3    sys_type     integer
       print     5    function    sys_type     integer
----------------------------------------
function: "print"
        name  line        type   attribute
          id     5    sys_type     integer
Type of AST Node: *****************
type of id: 18
    sys_type      string
type of id: 19
    sys_type     integer
type of id: 20
    sys_type     integer
type of id: 21
    sys_type     integer
type of id: 22
    sys_type     integer
type of id: 24
    sys_type     integer
type of id: 25
    sys_type     integer
type of id: 26
    sys_type     integer
type of id: 28
    sys_type     integer
