Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
      string     0    sys_type      string
        char     0    sys_type        char
           T     5       const     boolean           1
          pi     3       const        real     3.14159
     boolean     0    sys_type     boolean
           t     4       const     integer           3
        real     0    sys_type        real
     integer     0    sys_type     integer
Type of AST Node: *****************
type of id: 14
    sys_type     integer
type of id: 17
    sys_type     integer
type of id: 20
    sys_type      string
