Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
         str     3       const      string   "Hello World"
         tmp     6    sys_type     integer
       print     8    function    sys_type     integer
----------------------------------------
function: "print"
        name  line        type   attribute
          id    10    sys_type     integer
    sentence     9    sys_type      string
Type of AST Node: *****************
type of id: 25
    sys_type      string
type of id: 26
    sys_type      string
type of id: 27
    sys_type     integer
type of id: 28
    sys_type     integer
type of id: 29
    sys_type     integer
type of id: 30
    sys_type     integer
type of id: 35
    sys_type      string
type of id: 36
    sys_type     integer
type of id: 37
    sys_type     integer
type of id: 38
    sys_type     integer
type of id: 39
    sys_type     integer
type of id: 41
    sys_type      string
type of id: 42
    sys_type     integer
