Symbol Table: *****************
        name  line        type   attribute
        wrap     0   procedure
        info     0      record         Age:     sys_type     integer
                                       GPA:     sys_type        real
                                      Name:     sys_type      string
----------------------------------------
procedure: "wrap"
        name  line        type   attribute
         GPA     0    sys_type        real
        Name     0    sys_type      string
         Age     0    sys_type     integer
        name  line        type   attribute
        info     0      record         Age:     sys_type     integer
                                       GPA:     sys_type        real
                                      Name:     sys_type      string
Type of AST Node: *****************
type of id: 41
    sys_type     integer
type of id: 42
    sys_type     integer
type of id: 45
    sys_type     integer
type of id: 46
    sys_type      string
type of id: 47
    sys_type      string
type of id: 50
    sys_type      string
type of id: 51
    sys_type        real
type of id: 52
    sys_type        real
type of id: 55
    sys_type        real
type of id: 60
    sys_type     integer
type of id: 61
    sys_type      string
type of id: 62
    sys_type        real
type of id: 63
      record         Age:     sys_type     integer
                     GPA:     sys_type        real
                    Name:     sys_type      string
type of id: 66
    sys_type      string
type of id: 67
    sys_type      string
type of id: 70
    sys_type      string
type of id: 71
    sys_type     integer
type of id: 74
    sys_type      string
type of id: 75
    sys_type        real
