Symbol Table: *****************
Main entry has been set up!
        name  line        type   attribute
       index     7    sys_type     integer
           T     5       const     boolean           1
          pi     3       const        real     3.14159
           t     4       const     integer           3
Type of AST Node: *****************
type of id: 18
    sys_type     integer
type of id: 19
    sys_type     integer
type of id: 20
    sys_type     integer
type of id: 23
    sys_type      string
type of id: 24
    sys_type     integer
type of id: 25
    sys_type        real
