Symbol Table: *****************
        name  line        type   attribute
       Array     6       array       range    0 .. 100
                                  sys_type     integer
       index     8    sys_type     integer
      string     0    sys_type      string
        char     0    sys_type        char
     boolean     0    sys_type     boolean
      search     9    function    sys_type     boolean
     integer     0    sys_type     integer
        real     0    sys_type        real
     MAX_LEN     4       const     integer         100
        ZERO     3       const     integer           0
----------------------------------------
function: "search"
        name  line        type   attribute
         arr    11       array       range    0 .. 100
                                  sys_type     integer
        name  line        type   attribute
     element    12    sys_type     integer
        size    12    sys_type     integer
Type of AST Node: *****************
type of id: 38
    sys_type     integer
type of id: 39
    sys_type     integer
type of id: 40
    sys_type     integer
type of id: 42
    sys_type     integer
type of id: 44
    sys_type     boolean
type of id: 45
    sys_type     integer
type of id: 46
       array       range    0 .. 100
                sys_type     integer
type of id: 47
    sys_type     integer
type of id: 48
    sys_type     integer
type of id: 49
    sys_type     boolean
type of id: 50
    sys_type     boolean
type of id: 51
    sys_type     boolean
type of id: 53
    sys_type     boolean
type of id: 54
    sys_type     integer
type of id: 55
    sys_type     integer
type of id: 56
    sys_type     boolean
type of id: 57
    sys_type     boolean
type of id: 58
    sys_type     boolean
type of id: 59
    sys_type     integer
type of id: 60
    sys_type     integer
type of id: 61
    sys_type     integer
type of id: 62
    sys_type     integer
type of id: 63
    sys_type     integer
type of id: 65
    sys_type     integer
